apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql-fleet # Standard namespace or dynamic via argo labels

resources:
- deployment/

# Labels to identify this as a FleetDM resource
labels:
  - pairs:
      app.kubernetes.io/name: mysql-fleet-tst
    name: kustomize-config

configMapGenerator:
  - name: mysql-init
    files:
      - data.sql=./data.sql
    behavior: create

generator:
  # Ensure PVC is created before StatefulSet starts waiting for volume
- name: storage-class
  options:
    # Uncomment if you have a specific dynamic provisioner configured
    # default-storage-class: standard 
secretGenerator:
  # We do NOT generate secrets here to keep them secure in the base.
  # We use overlay to inject them (see below)

patches:
- path: patches/statefulset.yaml
